### ISSUE TITLE
Only the first code block is highlighted

### ISSUE THREAD

**Issue by ro-ka** [johannschopplich/kirby-highlighter#3]
When adding multiple explicit code blocks to a site, only the first is highlighted. Logging out the `$element` and the `$codeElement` in `HighlightAdapter.php`, the `$codeElement` is always the same (the first one).

This may also be the reason, why #1 crashes as it is maybe trying to delete a code block that isn’t there.

Any ideas? Usage of `DOMXPath->evaluate()` looks good to me.

**Comment by johannschopplich** [comment]
Weird. I will create tests that fail at the moment and look into it.

Thanks for testing!

**Comment by ro-ka** [comment]
Thanks for forking and taking a look!  😃

**Comment by johannschopplich** [comment]
I have dropped the use of `DOMXPath` and simplified the `pre` elements selection: https://github.com/johannschopplich/kirby-highlighter/commit/59b825ca908b078b683e551748e1fc0064fd1a40

Tests are also extended to always use two code blocks. Thus explicit *and* auto highlighting should work together on one page. Would you mind checking? I haven't pushed it to composer yet. Please download and copy the folder to your plugins directory. Thanks!

**Comment by ro-ka** [comment]
Just got the time to test it — and it works! 🎉  Thanks a lot!  😃

**Comment by johannschopplich** [comment]
Glad to hear!

**Comment by mtsknn** [comment]
I hadn't noticed that this issue had already been reported and fixed (because this issue has been closed but the update hasn't been published on Packagist yet), so I also investigated this.

A simple fix would have been to prefix the XPath expression with a period in [HighlightAdapter.php#L33](https://github.com/johannschopplich/kirby-highlighter/blob/v1.1.0/src/HighlightAdapter.php#L33):

```diff
-// Select direct `code` child element of `pre` block
-$codeElement = $query->evaluate('//code', $element)->item(0);
+// Select direct `code` child element of `pre` block. The period is
+// needed in the path for the selection to be relative to `$element`
+// @see https://www.php.net/manual/en/domxpath.query.php#99760
+$codeElement = $query->evaluate('.//code', $element)->item(0);
```

However, I think that the new code by @johannschopplich (59b825c) is better (XPaths are more complicated).

I tested the changes (`composer require johannschopplich/kirby-highlighter:dev-master`) and can confirm that multiple code blocks seem to work. 👍

**Comment by johannschopplich** [comment]
@mtsknn You're right! I forgot to draft a new release. Done. Thanks for pointing that out. 

Also glad to see how the former code should have been changed to work correctly. XPath isn't my jam obviously. Learned something again. 🙌

**Comment by mtsknn** [comment]
That was quick. 👍😄 Thanks!
